app:
  host: localhost
  port: 4000
  proxy:
    # 若 HTTP Proxy Headers 可信，则可设置 `proxy` 为 `true`。
    false
  secret: null
  session:
    key: moment

query:
  complexity-limit: 65535

redis:
  host: localhost
  port: 6379
  password: null
